(async function () {
    "use strict";
    const db = window.yuriArticles.getClient();
    const byId = (id) => document.getElementById(id);
    const draftKey = "yuri:export-profile-draft";
    const visibilityKeys = ["avatar","name","subtitle","bio","fandoms","favorites","boundaries","otome_profile","currently_playing","free_space","updated"];
    let profile = {}, settings = {}, fandoms = [], favorites = [], boundaries = [], otome = {}, games = [];
    let dirty = false, timer;
    const message = (text, error = false) => { byId("settings-message").textContent = text; byId("settings-message").classList.toggle("error", error); };
    const clean = (value) => String(value || "").trim();
    const collect = () => ({ overrides: { display_name: clean(byId("export-name").value), subtitle: clean(byId("export-subtitle").value), bio: clean(byId("export-bio").value), about: clean(byId("export-about").value), avatar_url: clean(byId("export-avatar").value), fandoms: clean(byId("export-fandoms").value), favorites: clean(byId("export-favorites").value), boundaries: clean(byId("export-boundaries").value), otome_profile: clean(byId("export-otome").value), currently_playing: clean(byId("export-currently").value), free_space: clean(byId("export-free").value) }, visibility: Object.fromEntries(visibilityKeys.map((key) => [key, document.querySelector(`[data-visibility="${key}"]`).checked])) });
    function apply(value = {}) { const o=value.overrides||{},v=value.visibility||{}; byId("export-name").value=o.display_name||"";byId("export-subtitle").value=o.subtitle||"";byId("export-bio").value=o.bio||"";byId("export-about").value=o.about||"";byId("export-avatar").value=o.avatar_url||"";byId("export-fandoms").value=o.fandoms||"";byId("export-favorites").value=o.favorites||"";byId("export-boundaries").value=o.boundaries||"";byId("export-otome").value=o.otome_profile||"";byId("export-currently").value=o.currently_playing||"";byId("export-free").value=o.free_space||"";visibilityKeys.forEach(k=>document.querySelector(`[data-visibility="${k}"]`).checked=v[k]!==false); renderPreview(); }
    const fallback=(override,value)=>clean(override)||clean(value);
    const listText=(override,items,describe)=>clean(override)||items.map(item=>[item.name||item.label,describe(item)].filter(Boolean).join(" / ")).join(" · ");
    function section(container,title,text,axis=false){if(!text)return;const s=document.createElement("section");s.className="export-preview-section";const h=document.createElement("h4");h.textContent=title;const p=document.createElement("p");p.textContent=text;s.append(h,p);if(axis){const bar=document.createElement("div");bar.className="export-preview-axis";s.append(bar)}container.append(s)}
    function renderPreview(){if(!profile.id)return;const c=collect(),o=c.overrides,v=c.visibility,current=settings.currently_playing||{},linked=games.find(g=>String(g.id)===String(current.game_id));const preview=byId("export-preview");preview.replaceChildren();const mast=document.createElement("div");mast.className="export-preview-mast";mast.innerHTML="<b>KIORA.SPACE</b><span>PERSONAL ARCHIVE</span><span>PROFILE SHEET</span>";const body=document.createElement("div");body.className="export-preview-body";const identity=document.createElement("div");identity.className="export-preview-identity";if(v.avatar){const portrait=document.createElement("div");portrait.className="export-preview-portrait";const avatar=fallback(o.avatar_url,profile.avatar_url);if(avatar){const img=document.createElement("img");img.src=avatar;img.alt="";portrait.append(img)}else portrait.textContent="✦";identity.append(portrait)}if(v.name){const h=document.createElement("h3");h.textContent=fallback(o.display_name,profile.nickname)||"PROFILE";identity.append(h)}if(v.subtitle){const p=document.createElement("p");p.textContent=fallback(o.subtitle,profile.tagline);identity.append(p)}if(v.bio){const p=document.createElement("p");p.textContent=[fallback(o.bio,profile.summary),fallback(o.about,profile.about_text)].filter(Boolean).join(" / ");identity.append(p)}const sections=document.createElement("div");sections.className="export-preview-sections";if(v.fandoms)section(sections,"FANDOMS",listText(o.fandoms,fandoms,i=>i.description||i.status));if(v.favorites)section(sections,"FAVORITES",listText(o.favorites,favorites,i=>[i.work_name,i.favorite_level].filter(Boolean).join(" / ")));if(v.boundaries)section(sections,"NG",listText(o.boundaries,boundaries,i=>i.kind));if(v.otome_profile)section(sections,"OTOME PROFILE",fallback(o.otome_profile,[...(otome.play_styles||[]),...(otome.favorite_elements||[]),...(otome.not_my_type||[])].join(" / ")),true);if(v.currently_playing)section(sections,"CURRENTLY PLAYING",fallback(o.currently_playing,[current.title||linked?.title,current.subtitle,current.status,current.note].filter(Boolean).join(" / ")));if(v.free_space)section(sections,"FREE SPACE",fallback(o.free_space,profile.free_space_content));body.append(identity,sections);const footer=document.createElement("div");footer.className="export-preview-footer";footer.innerHTML=`<span>KIORA.SPACE</span><span>${v.updated?"UPDATED / PREVIEW":""}</span>`;preview.append(mast,body,footer)}
    function schedule(){dirty=true;byId("settings-save-state").textContent="UNSAVED";renderPreview();clearTimeout(timer);timer=setTimeout(()=>{localStorage.setItem(draftKey,JSON.stringify(collect()));byId("settings-save-state").textContent="DRAFT SAVED"},2500)}
    byId("export-form").addEventListener("input",schedule);window.addEventListener("beforeunload",e=>{if(!dirty)return;localStorage.setItem(draftKey,JSON.stringify(collect()));e.preventDefault();e.returnValue=""});byId("settings-back").addEventListener("click",()=>{if(dirty&&!confirm("还有未保存的导出设置，确定返回吗？草稿会保留在此设备。"))return;location.href="about.html"});
    await window.KioraAuth.initialize(db);if(window.KioraAuth.role!=="owner"){byId("settings-gate").textContent="此页面仅限站点所有者使用，正在返回首页……";setTimeout(()=>location.href="index.html",900);return}
    const results=await Promise.all([db.from("site_profile").select("*").eq("id",1).maybeSingle(),db.from("site_settings").select("*").eq("id",1).maybeSingle(),db.from("profile_fandoms").select("*").order("sort_order"),db.from("profile_favorites").select("*").order("sort_order"),db.from("profile_boundaries").select("*").order("sort_order"),db.from("otome_profile").select("*").eq("id",1).maybeSingle(),db.from("games").select("id,title").order("sort_order")]);const failed=results.find(r=>r.error);if(failed){byId("settings-gate").textContent=failed.error.message;return}profile=results[0].data||{};settings=results[1].data||{};fandoms=results[2].data||[];favorites=results[3].data||[];boundaries=results[4].data||[];otome=results[5].data||{};games=results[6].data||[];apply(settings.export_profile_settings||{});const draft=localStorage.getItem(draftKey);if(draft&&confirm("检测到未保存的 Export Profile 草稿，是否恢复？")){try{apply(JSON.parse(draft));dirty=true}catch(_){localStorage.removeItem(draftKey)}}
    byId("export-avatar-default").addEventListener("click",()=>{byId("export-avatar").value="";schedule()});
    async function uploadAvatar(){const file=byId("export-avatar-file").files[0];if(!file)return clean(byId("export-avatar").value);if(!file.type.startsWith("image/")||file.size>5*1024*1024)throw new Error("请选择不超过 5MB 的图片。");const ext=(file.name.split(".").pop()||"jpg").replace(/[^a-z0-9]/gi,"");const path=`profile-export/${crypto.randomUUID()}.${ext}`;const{error}=await db.storage.from("site-media").upload(path,file,{contentType:file.type});if(error)throw error;return db.storage.from("site-media").getPublicUrl(path).data.publicUrl}
    byId("export-form").addEventListener("submit",async e=>{e.preventDefault();message("Saving…");let avatar;try{avatar=await uploadAvatar()}catch(error){message(error.message,true);return}const payload=collect();payload.overrides.avatar_url=avatar;const{error}=await db.from("site_settings").upsert({id:1,export_profile_settings:payload},{onConflict:"id"});if(error){message(`保存失败：${error.message}。请先运行最新的 Supabase 设置迁移。`,true);return}localStorage.removeItem(draftKey);dirty=false;byId("settings-save-state").textContent="SAVED";message("Saved / 已保存");apply(payload)});
    byId("export-reset").addEventListener("click",async()=>{if(!confirm("清除所有导出覆写并恢复 Profile 默认值吗？"))return;const{error}=await db.from("site_settings").upsert({id:1,export_profile_settings:null},{onConflict:"id"});if(error)return message(`恢复失败：${error.message}`,true);localStorage.removeItem(draftKey);dirty=false;settings.export_profile_settings=null;apply({});byId("settings-save-state").textContent="SAVED";message("已恢复 Profile 默认内容。");});
    byId("settings-gate").hidden=true;byId("export-editor").hidden=false;byId("settings-save-state").textContent="READY";renderPreview();
})();

