-- Kiora game Repo export settings.
-- Run once in Supabase Dashboard > SQL Editor before using SAVE REPO.

begin;

create or replace function public.set_updated_at()
returns trigger language plpgsql security invoker set search_path = public as $$
begin new.updated_at = now(); return new; end;
$$;

create table if not exists public.game_repo (
    id bigint generated by default as identity primary key,
    game_id bigint not null unique references public.games(id) on delete cascade,
    owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
    config jsonb not null default '{}'::jsonb check (jsonb_typeof(config) = 'object'),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists game_repo_game_id_idx on public.game_repo(game_id);

drop trigger if exists game_repo_set_updated_at on public.game_repo;
create trigger game_repo_set_updated_at before update on public.game_repo
for each row execute function public.set_updated_at();

alter table public.game_repo enable row level security;

drop policy if exists "Owners read game repo" on public.game_repo;
create policy "Owners read game repo" on public.game_repo for select to authenticated
using (auth.uid() = owner_id);

drop policy if exists "Owners create game repo" on public.game_repo;
create policy "Owners create game repo" on public.game_repo for insert to authenticated
with check (auth.uid() = owner_id);

drop policy if exists "Owners update game repo" on public.game_repo;
create policy "Owners update game repo" on public.game_repo for update to authenticated
using (auth.uid() = owner_id) with check (auth.uid() = owner_id);

drop policy if exists "Owners delete game repo" on public.game_repo;
create policy "Owners delete game repo" on public.game_repo for delete to authenticated
using (auth.uid() = owner_id);

grant select, insert, update, delete on public.game_repo to authenticated;
grant usage, select on sequence public.game_repo_id_seq to authenticated;

commit;
