-- Kiora MUSIC ARCHIVE
-- Safe additive migration. Existing tables, data, authentication and policies are unchanged.

begin;

create table if not exists public.music (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    owner_id uuid not null default auth.uid() references auth.users(id) on delete restrict,
    title text not null check (char_length(title) between 1 and 240),
    artist text,
    cover_url text,
    music_url text not null check (music_url ~ '^https?://'),
    provider text not null check (provider in ('netease', 'spotify', 'youtube', 'apple_music')),
    note text,
    lyric_excerpt text,
    lrc_data text,
    sort_order integer
);

create index if not exists music_archive_order_idx
    on public.music (sort_order, created_at);
create index if not exists music_owner_idx
    on public.music (owner_id);

create or replace function public.set_music_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists music_set_updated_at on public.music;
create trigger music_set_updated_at
before update on public.music
for each row execute function public.set_music_updated_at();

alter table public.music enable row level security;

drop policy if exists "Public reads music archive" on public.music;
create policy "Public reads music archive"
on public.music for select
to anon, authenticated
using (true);

drop policy if exists "Owners insert music archive" on public.music;
create policy "Owners insert music archive"
on public.music for insert
to authenticated
with check (auth.uid() = owner_id);

drop policy if exists "Owners update music archive" on public.music;
create policy "Owners update music archive"
on public.music for update
to authenticated
using (auth.uid() = owner_id)
with check (auth.uid() = owner_id);

drop policy if exists "Owners delete music archive" on public.music;
create policy "Owners delete music archive"
on public.music for delete
to authenticated
using (auth.uid() = owner_id);

revoke select on public.music from anon, authenticated;
grant select (
    id, created_at, updated_at, title, artist, cover_url, music_url,
    provider, note, lyric_excerpt, lrc_data, sort_order
) on public.music to anon, authenticated;
grant insert, update, delete on public.music to authenticated;
grant usage, select on sequence public.music_id_seq to authenticated;

-- Join the existing automatic UPDATED tracker when that optional system is installed.
do $$
begin
    if to_regclass('public.site_settings') is not null
       and to_regprocedure('public.touch_site_content_updated_at()') is not null then
        drop trigger if exists site_updated_from_music on public.music;
        create trigger site_updated_from_music
        after insert or update or delete on public.music
        for each statement execute function public.touch_site_content_updated_at();
    end if;
end;
$$;

commit;
