-- Kiora Games Archive / Tier Board
-- Safe additive migration. Run in Supabase Dashboard > SQL Editor.
-- Existing game rows and columns are preserved.

begin;

create or replace function public.set_updated_at()
returns trigger language plpgsql security invoker set search_path = public as $$
begin new.updated_at = now(); return new; end;
$$;

alter table public.games
    add column if not exists status text,
    add column if not exists platforms text[] not null default '{}',
    add column if not exists tags text[] not null default '{}',
    add column if not exists favorite_level text,
    add column if not exists official_site_url text,
    add column if not exists store_links jsonb not null default '[]'::jsonb,
    add column if not exists updated_at timestamptz not null default now();

do $$ begin
    alter table public.games add constraint games_status_check
        check (status is null or status in ('PLAYING','COMPLETED','PAUSED','DROPPED','WISHLIST')) not valid;
exception when duplicate_object then null; end $$;

do $$ begin
    alter table public.games add constraint games_favorite_level_check
        check (favorite_level is null or favorite_level in ('FAVORITE','LOVE','LIKE','NEUTRAL','NOT FOR ME')) not valid;
exception when duplicate_object then null; end $$;

drop trigger if exists games_set_updated_at on public.games;
create trigger games_set_updated_at before update on public.games
for each row execute function public.set_updated_at();

create table if not exists public.tier_boards (
    id bigint generated by default as identity primary key,
    owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
    title text not null,
    description text,
    sort_order integer,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.tier_sections (
    id bigint generated by default as identity primary key,
    board_id bigint not null references public.tier_boards(id) on delete cascade,
    title text not null,
    description text,
    sort_order integer,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.tier_items (
    id bigint generated by default as identity primary key,
    board_id bigint not null references public.tier_boards(id) on delete cascade,
    section_id bigint not null references public.tier_sections(id) on delete cascade,
    game_id bigint not null references public.games(id) on delete cascade,
    sort_order integer,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (board_id, game_id)
);

drop trigger if exists tier_boards_set_updated_at on public.tier_boards;
create trigger tier_boards_set_updated_at before update on public.tier_boards for each row execute function public.set_updated_at();
drop trigger if exists tier_sections_set_updated_at on public.tier_sections;
create trigger tier_sections_set_updated_at before update on public.tier_sections for each row execute function public.set_updated_at();
drop trigger if exists tier_items_set_updated_at on public.tier_items;
create trigger tier_items_set_updated_at before update on public.tier_items for each row execute function public.set_updated_at();

create index if not exists tier_boards_sort_idx on public.tier_boards(sort_order, created_at);
create index if not exists tier_sections_board_sort_idx on public.tier_sections(board_id, sort_order, created_at);
create index if not exists tier_items_section_sort_idx on public.tier_items(section_id, sort_order, created_at);

alter table public.tier_boards enable row level security;
alter table public.tier_sections enable row level security;
alter table public.tier_items enable row level security;

drop policy if exists "Public reads tier boards" on public.tier_boards;
create policy "Public reads tier boards" on public.tier_boards for select to anon, authenticated using (true);
drop policy if exists "Owners manage tier boards" on public.tier_boards;
create policy "Owners manage tier boards" on public.tier_boards for all to authenticated using (auth.uid() = owner_id) with check (auth.uid() = owner_id);

drop policy if exists "Public reads tier sections" on public.tier_sections;
create policy "Public reads tier sections" on public.tier_sections for select to anon, authenticated using (true);
drop policy if exists "Owners manage tier sections" on public.tier_sections;
create policy "Owners manage tier sections" on public.tier_sections for all to authenticated
using (exists (select 1 from public.tier_boards b where b.id = board_id and b.owner_id = auth.uid()))
with check (exists (select 1 from public.tier_boards b where b.id = board_id and b.owner_id = auth.uid()));

drop policy if exists "Public reads tier items" on public.tier_items;
create policy "Public reads tier items" on public.tier_items for select to anon, authenticated using (true);
drop policy if exists "Owners manage tier items" on public.tier_items;
create policy "Owners manage tier items" on public.tier_items for all to authenticated
using (exists (select 1 from public.tier_boards b where b.id = board_id and b.owner_id = auth.uid()))
with check (exists (select 1 from public.tier_boards b where b.id = board_id and b.owner_id = auth.uid()));

grant select (id, title, description, sort_order, created_at, updated_at) on public.tier_boards to anon, authenticated;
grant select on public.tier_sections, public.tier_items to anon, authenticated;
grant insert, update, delete on public.tier_boards, public.tier_sections, public.tier_items to authenticated;
grant usage, select on all sequences in schema public to authenticated;

do $$
declare table_name text;
begin
    if to_regprocedure('public.touch_site_content_updated_at()') is not null then
        foreach table_name in array array['tier_boards','tier_sections','tier_items'] loop
            execute format('drop trigger if exists %I on public.%I', 'site_updated_from_' || table_name, table_name);
            execute format('create trigger %I after insert or update or delete on public.%I for each statement execute function public.touch_site_content_updated_at()', 'site_updated_from_' || table_name, table_name);
        end loop;
    end if;
end $$;

commit;
