-- Kiora site CMS tables
-- Run once in Supabase Dashboard > SQL Editor.
-- Existing games, characters and authentication data are not changed.

begin;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create table if not exists public.site_profile (
    id smallint primary key default 1 check (id = 1),
    nickname text,
    avatar_url text,
    tagline text,
    summary text,
    about_text text,
    free_space_title text,
    free_space_content text,
    updated_at timestamptz not null default now()
);

create table if not exists public.profile_fandoms (
    id bigint generated by default as identity primary key,
    name text not null check (char_length(name) between 1 and 120),
    image_url text,
    description text,
    status text not null default 'CURRENT'
        check (status in ('CURRENT', 'LONG TERM', 'OCCASIONAL', 'CLOSED')),
    sort_order integer,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.profile_favorites (
    id bigint generated by default as identity primary key,
    name text not null check (char_length(name) between 1 and 120),
    work_name text,
    image_url text,
    favorite_level text not null default '推'
        check (favorite_level in ('最推', '推', '好感')),
    note text,
    symbol text,
    sort_order integer,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.profile_boundaries (
    id bigint generated by default as identity primary key,
    label text not null check (char_length(label) between 1 and 240),
    kind text not null default '苦手'
        check (kind in ('雷点', '苦手', '不太感兴趣')),
    sort_order integer,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.otome_profile (
    id smallint primary key default 1 check (id = 1),
    axes jsonb not null default '[]'::jsonb check (jsonb_typeof(axes) = 'array'),
    play_styles text[] not null default '{}',
    favorite_elements text[] not null default '{}',
    not_my_type text[] not null default '{}',
    updated_at timestamptz not null default now()
);

create table if not exists public.writings (
    id bigint generated by default as identity primary key,
    title text not null check (char_length(title) between 1 and 240),
    subtitle text,
    body text not null,
    category text not null
        check (category in ('game_review', 'essay', 'dream', 'archive')),
    published_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    cover_url text,
    tags text[] not null default '{}',
    is_pinned boolean not null default false,
    is_public boolean not null default true,
    excerpt text,
    sort_order integer
);

create index if not exists writings_public_order_idx
    on public.writings (category, is_public, is_pinned desc, sort_order, published_at desc);
create index if not exists profile_fandoms_order_idx
    on public.profile_fandoms (sort_order, created_at);
create index if not exists profile_favorites_order_idx
    on public.profile_favorites (sort_order, created_at);
create index if not exists profile_boundaries_order_idx
    on public.profile_boundaries (sort_order, created_at);

drop trigger if exists site_profile_set_updated_at on public.site_profile;
create trigger site_profile_set_updated_at
before update on public.site_profile
for each row execute function public.set_updated_at();

drop trigger if exists fandoms_set_updated_at on public.profile_fandoms;
create trigger fandoms_set_updated_at
before update on public.profile_fandoms
for each row execute function public.set_updated_at();

drop trigger if exists favorites_set_updated_at on public.profile_favorites;
create trigger favorites_set_updated_at
before update on public.profile_favorites
for each row execute function public.set_updated_at();

drop trigger if exists boundaries_set_updated_at on public.profile_boundaries;
create trigger boundaries_set_updated_at
before update on public.profile_boundaries
for each row execute function public.set_updated_at();

drop trigger if exists otome_profile_set_updated_at on public.otome_profile;
create trigger otome_profile_set_updated_at
before update on public.otome_profile
for each row execute function public.set_updated_at();

drop trigger if exists writings_set_updated_at on public.writings;
create trigger writings_set_updated_at
before update on public.writings
for each row execute function public.set_updated_at();

insert into public.site_profile (id) values (1) on conflict (id) do nothing;
insert into public.otome_profile (id) values (1) on conflict (id) do nothing;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'site-media',
    'site-media',
    true,
    5242880,
    array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

alter table public.site_profile enable row level security;
alter table public.profile_fandoms enable row level security;
alter table public.profile_favorites enable row level security;
alter table public.profile_boundaries enable row level security;
alter table public.otome_profile enable row level security;
alter table public.writings enable row level security;

drop policy if exists "Public can read site profile" on public.site_profile;
create policy "Public can read site profile"
on public.site_profile for select
to anon, authenticated
using (true);

drop policy if exists "Public can read fandoms" on public.profile_fandoms;
create policy "Public can read fandoms"
on public.profile_fandoms for select
to anon, authenticated
using (true);

drop policy if exists "Public can read favorites" on public.profile_favorites;
create policy "Public can read favorites"
on public.profile_favorites for select
to anon, authenticated
using (true);

drop policy if exists "Public can read boundaries" on public.profile_boundaries;
create policy "Public can read boundaries"
on public.profile_boundaries for select
to anon, authenticated
using (true);

drop policy if exists "Public can read otome profile" on public.otome_profile;
create policy "Public can read otome profile"
on public.otome_profile for select
to anon, authenticated
using (true);

drop policy if exists "Public reads published writings" on public.writings;
create policy "Public reads published writings"
on public.writings for select
to anon
using (is_public = true);

drop policy if exists "Admin reads all writings" on public.writings;
create policy "Admin reads all writings"
on public.writings for select
to authenticated
using (true);

do $$
declare
    table_name text;
begin
    foreach table_name in array array[
        'site_profile',
        'profile_fandoms',
        'profile_favorites',
        'profile_boundaries',
        'otome_profile',
        'writings'
    ]
    loop
        execute format('drop policy if exists "Admin inserts %1$s" on public.%1$I', table_name);
        execute format('create policy "Admin inserts %1$s" on public.%1$I for insert to authenticated with check (true)', table_name);
        execute format('drop policy if exists "Admin updates %1$s" on public.%1$I', table_name);
        execute format('create policy "Admin updates %1$s" on public.%1$I for update to authenticated using (true) with check (true)', table_name);
        execute format('drop policy if exists "Admin deletes %1$s" on public.%1$I', table_name);
        execute format('create policy "Admin deletes %1$s" on public.%1$I for delete to authenticated using (true)', table_name);
    end loop;
end;
$$;

grant select on public.site_profile, public.profile_fandoms, public.profile_favorites,
    public.profile_boundaries, public.otome_profile to anon, authenticated;
grant insert, update, delete on public.site_profile, public.profile_fandoms,
    public.profile_favorites, public.profile_boundaries, public.otome_profile,
    public.writings to authenticated;
grant select on public.writings to anon, authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "Public reads site media" on storage.objects;
create policy "Public reads site media"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'site-media');

drop policy if exists "Admin uploads site media" on storage.objects;
create policy "Admin uploads site media"
on storage.objects for insert
to authenticated
with check (bucket_id = 'site-media');

drop policy if exists "Admin updates site media" on storage.objects;
create policy "Admin updates site media"
on storage.objects for update
to authenticated
using (bucket_id = 'site-media')
with check (bucket_id = 'site-media');

drop policy if exists "Admin deletes site media" on storage.objects;
create policy "Admin deletes site media"
on storage.objects for delete
to authenticated
using (bucket_id = 'site-media');

commit;
